functionsDirectory = "D:\\Portfolio\\CameronsAirHVac\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
headersOrigin = "config"
plugins = []
redirects = []

[build]
publish = "D:\\Portfolio\\CameronsAirHVac"
publishOrigin = "config"
commandOrigin = "config"
base = "D:\\Portfolio\\CameronsAirHVac"
command = "npm install"
functions = "D:\\Portfolio\\CameronsAirHVac\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[headers]]
for = "/*"

[headers.values]
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' blob: data: https://www.google.com/recaptcha/api.js https://apis.google.com/js/client.js https://apis.google.com/js/api.js https://www.googletagmanager.com/gtag/js https://www.google.com/tools/feedback/chat_load.js https://www.google.com/tools/feedback/help_api.js https://www.google.com/tools/feedback/load.js https://www.google.com/tools/feedback/open.js https://www.google.com/tools/feedback/open_to_help_guide_lazy.js https://www.gstatic.com/feedback/js/ https://www.gstatic.com/feedback/js/help/prod/service/lazy.min.js https://www.gstatic.com/inproduct_help/api/main.min.js https://www.gstatic.com/inproduct_help/chatsupport/chatsupport_button_v2.js https://www.gstatic.com/inproduct_help/service/lazy.min.js https://www.gstatic.com/uservoice/feedback/client/web/live/ https://www.gstatic.com/uservoice/surveys/resources/prod/js/survey/ https://www.gstatic.com/_/mss/boq-calendar/_/js/k=boq-calendar.CalendarWebAppSlots.en_US.tCuVsYx8ag8.2020.O/ https://apis.google.com/_/scs/abc-static/_/js/ https://www.gstatic.com/recaptcha/releases/ https://calendar.google.com/calendar/scheduling-button-script.js; style-src 'self' https://fonts.googleapis.com https://calendar.google.com; font-src 'self' data: https://fonts.gstatic.com; frame-src https://www.google.com https://calendar.google.com;"

[[headers]]
for = "/.netlify/functions/*"

[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET, POST, OPTIONS"
Access-Control-Allow-Headers = "Content-Type"